<?php
    include("loadclass.php");

    $id = $_POST['id'];
    // echo $id;
    // echo "<script>console.log(.$id.) </script>";

    $foodbank = new Foodbank();
    $foodbankDetails = $foodbank->getdetailFoodbank($id); 
    // echo "<pre>";
    // print_r($foodbankDetails);
    // echo "</pre>";

echo' <form class="needs-validation" action="editFoodbank.php" method="post" novalidate>';
echo'    <div class="row g-3 px-4 py-4">';
echo'        <input';
echo '          type="hidden"';
echo'           value="'.$foodbankDetails[0]['fb_id'].'"';
echo '          class="form-control rounded-3"';
echo '          name="id"';
echo '          id="floatingName"/>';
echo'        <div class="col-sm-12">';
echo'        <label for="foodbankName" class="form-label">Foodbank Name</label>';
echo'        <input type="text" class="form-control" id="foodbankName" name="fb_name" value="'.$foodbankDetails[0]['Fb_name'].'" required>';

echo'        </div>';
echo'        ';
echo'        <div class="col-sm-12">';
echo'        <label for="foodBankNumber" class="form-label">Phone Number</label>';
echo'        <input type="text" class="form-control" id="phoneNumber" name="phone" value="'.$foodbankDetails[0]['Phone'].'" required>';
echo'        </div>';
echo'        ';
echo'        <div class="col-md-6">';
echo'        <label for="openTime" class="form-label">Opening Time</label>';
echo'            <select class="form-select" id="openTime" name="openTime" required>';
echo'                <option value="'.$foodbankDetails[0]['OpeningTime'].'" selected hidden>'.$foodbankDetails[0]['OpeningTime'].'</option>';
echo'                <option value="7.00am">7.00am</option>';
echo'                <option value="7.30am">7.30am</option>';
echo'                <option value="8.00am">8.00am</option>';
echo'                <option value="8.30am">8.30am</option>';
echo'                <option value="9.00am">9.00am</option>';
echo'                <option value="9.30am">9.30am</option>';
echo'                <option value="10.00am">10.00am</option>';
echo'                <option value="10.30am">10.30am</option>';
echo'                <option value="11.00am">11.00am</option>';
echo'                <option value="11.30am">11.30am</option>';
echo'                <option value="12.00pm">12.00pm</option>';
echo'            </select>';
echo'            <div class="invalid-feedback">';
echo'                Please provide a valid time.';
echo'            </div>'; 
echo'        </div>';
echo'        ';
echo'        <div class="col-md-6">'; 
echo'        <label for="closeTime" class="form-label">Closing Time</label>';
echo'        <select class="form-select" id="closeTime" name="closeTime" required>';
echo'                <option value="'.$foodbankDetails[0]['ClosingTime'].'" selected hidden>'.$foodbankDetails[0]['ClosingTime'].'</option>';
echo'                <option value="5.00pm">5.00pm</option>';
echo'                <option value="5.30pm">5.30pm</option>';
echo'                <option value="6.00pm">6.00pm</option>';
echo'                <option value="6.30pm">6.30pm</option>';
echo'                <option value="7.00pm">7.00pm</option>';
echo'                <option value="7.30pm">7.30pm</option>';
echo'                <option value="8.00pm">8.00pm</option>';
echo'                <option value="8.30pm">8.30pm</option>';
echo'                <option value="9.00pm">9.00pm</option>';
echo'                <option value="9.30pm">9.30pm</option>';
echo'                <option value="10.00pm">10.00pm</option>';
echo'            </select>';
echo'            <div class="invalid-feedback">';
echo'                Please provide a valid time.';
echo'            </div>'; 
echo'        </div>';
echo'';
echo'        <div class="col-12">';
echo'        <label for="foodBankEmail" class="form-label">Email</label>';
echo'        <input type="email" class="form-control" id="email" name="email" value="'.$foodbankDetails[0]['Email'].'" ';
echo'        </div>';
echo'';
echo'        <div class="col-12">';
echo'        <label for="foodBankAddress" class="form-label">Address</label>';
echo'        <input type="text" class="form-control" id="address" name="address" value="'.$foodbankDetails[0]['Address'].'" required>';
echo'        </div>';
echo'';
echo'        <div class="col-12">';
echo'        <label for="foodBankAddress2" class="form-label">Address 2 </label>';
echo'        <input type="text" class="form-control" id="address2" name="address2" value="'.$foodbankDetails[0]['Address2'].'">';
echo'        </div>	';
echo'        ';

echo' <div class="col-md-6">';
echo'     <label for="foodBankState" class="form-label">State</label>';
echo'     <select class="form-select" id="state" name="state" required>';
echo'         <option value="'.$foodbankDetails[0]['State'].'" selected hidden>'.$foodbankDetails[0]['State'].'</option>';
echo'         <option value="Johor">Johor</option>';
echo'         <option value="Kedah">Kedah</option>';
echo'         <option value="Kelantan">Kelantan</option>';
echo'         <option value="Malacca">Malacca</option>';
echo'         <option value="Negeri Sembilan">Negeri Sembilan</option>';
echo'         <option value="Pahang">Pahang</option>';
echo'         <option value="Penang">Penang</option>';
echo'         <option value="Perak">Perak</option>';
echo'         <option value="Perlis">Perlis</option>';
echo'         <option value="Sabah">Sabah</option>';
echo'         <option value="Sarawak">Sarawak</option>';
echo'         <option value="Selangor">Selangor</option>';
echo'         <option value="Terengganu">Terengganu</option>';
echo'         <option value="W.P. Kuala Lumpur">W.P. Kuala Lumpur</option>';
echo'         <option value="W.P. Labuan">W.P. Labuan</option>';
echo'         <option value="W.P. Putrajaya">W.P. Putrajaya</option>';
echo'     </select>';
echo'     <div class="invalid-feedback">';
echo'         Please provide a valid state.';
echo'     </div>';
echo' </div>';

echo'        <div class="col-md-6">';
echo'            <label for="foodBankCity" class="form-label">City</label>';
echo'            <input type="text" class="form-control" id="city" name="city" value="'.$foodbankDetails[0]['City'].'" required>';
echo'            </div>';
echo'        </div>';
echo'        ';
echo'        <div class="col-md-6">';
echo'        <label for="foodBankPostcode" class="form-label">Postcode</label>';
echo'        <input type="text" class="form-control" id="postcode" name="postcode" value="'.$foodbankDetails[0]['Postcode'].'" required>';
echo'        </div>';
echo'        <div class="col-12">';
echo'            <label for="foodbankDescription" class="form-label">Description <span class="text-muted">(Optional)</span></label>';
echo'            <textarea class="form-control" id="description" name="description">'.$foodbankDetails[0]['Description'].' </textarea>';
echo'        </div>	';
echo'    </div>';
echo'    <div class="mb-5 text-center"><button class="w-50 btn btn-primary btn-lg" type="submit">Update</button></div>';
echo'    </form>';
?>
<script src="script/validation.js"></script>