<?php
    include("loadclass.php");

    $id = $_POST['id'];
    // echo $id;
    // echo "<script>console.log(.$id.) </script>";

    $receiver = new Receiver();
    $receiverDetails = $receiver->getdetailReceiver($id); 
    // echo "<pre>";
    // print_r($foodbankDetails);
    // echo "</pre>";
echo'    <div class="modal-body p-5 pt-0">';
echo'    <form class="needs-validation" action="addReceiver.php" method="POST" novalidate >';
echo'        <div class="row g-3">';
echo'            <div class="col-sm-12">';
echo'            <label for="receiverName" class="form-label">Receiver Name</label>';
echo'            <input type="text" class="form-control" id="receiverName" name="name" placeholder="Receiver ABC" value="'.$receiverDetails[0]['Name'].'" readonly>';
echo'            <div class="invalid-feedback">';
echo'                Valid receiver name is required.';
echo'            </div>';
echo'            </div>';
echo'            ';
echo'            <div class="col-sm-12">';
echo'            <label for="receiverNumber" class="form-label">Phone Number</label>';
echo'            <input type="text" class="form-control" id="phoneNumber" name="phone" placeholder="012-34567890" value="'.$receiverDetails[0]['Phone'].'" readonly>';
echo'            <div class="invalid-feedback">';
echo'                Valid phone number is required.';
echo'            </div>';
echo'            </div>';
echo'            ';
echo'            <div class="col-md-6">';
echo'            <label for="age" class="form-label">Age</label>';
echo'            <input type="text" class="form-control" id="age" name="age" placeholder="21" value="'.$receiverDetails[0]['Age'].'" readonly>';
echo'            <div class="invalid-feedback">';
echo'                Valid age is required.';
echo'            </div>';
echo'            </div>';
echo'            ';
echo'            <div class="col-md-6">';
echo'            <label for="gender" class="form-label">Gender</label>';
echo'               <input type="text" class="form-control" id="gender" name="gender" value="'.$receiverDetails[0]['Gender'].'" readonly>';
echo'            <div class="invalid-feedback">';
echo'                Please provide a valid gender.';
echo'            </div>';
echo'            </div>';
echo'';
echo'            <div class="col-12">';
echo'            <label for="receiverAddress" class="form-label">Address</label>';
echo'            <input type="text" class="form-control" name="address" id="address" placeholder="1234 Main St" value="'.$receiverDetails[0]['Address'].'" readonly>';
echo'            <div class="invalid-feedback">';
echo'                Please enter a foodbank address.';
echo'            </div>';
echo'            </div>';
echo'';
echo'            <div class="col-12">';
echo'            <label for="receiverAddress2" class="form-label">Address 2 <span class="text-muted">(Optional)</span></label>';
echo'            <input type="text" class="form-control" name="address2" id="address2" placeholder="Apartment or suite" value="'.$receiverDetails[0]['Address2'].'" readonly>';
echo'            </div>	';
echo'            ';
echo'            <div class="col-md-6">';
echo'            <label for="receiverState" class="form-label">State</label>';
echo'            <input type="text" class="form-control" name="state" id="state" placeholder="1234 Main St" value="'.$receiverDetails[0]['State'].'" readonly>';
echo'            <div class="invalid-feedback">';
echo'                Please provide a valid state.';
echo'            </div>';
echo'            </div>';
echo'';
echo'            <div class="col-md-6">';
echo'                <label for="receiverCity" class="form-label">City</label>';
echo'                <input type="text" class="form-control" name="city" id="city" placeholder="City" value="'.$receiverDetails[0]['Postcode'].'" readonly>';
echo'                <div class="invalid-feedback">';
echo'                    Postcode required.';
echo'                </div>';
echo'                </div>';
echo'            </div>';
echo'            ';

            
echo'            <div class="col-12 pt-2">';
echo'                <label for="receiverNote" class="form-label">Note <span class="text-muted">(Optional)</span></label>';
echo'                <textarea class="form-control" id="note" name="note" placeholder="Foodbank Information" readonly> '.$receiverDetails[0]['Note'].' </textarea>';
echo'            </div>	';
echo'       </div>';
echo'        </div>';
echo'        <div class="mb-5 text-center"><button class="w-50 btn btn-primary btn-lg" type="submit">Add Receiver</button></div>';
echo'    </form>';
echo'</div>';
?>